# Generated by Django 5.2.6 on 2025-09-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitechblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entry_images/'),
        ),
    ]
